# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Apps by MLZ
email: mlz.1991.d+support@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  All apps by MLZ in one place – ready for you to explore and enjoy. The Shopping Calculator app helps you keep an eye on your spending and budget, perfect for tasks like grocery shopping. Create your own dice with the Custom Dice app by painting them and then using them for games. The Photo Match Game lets you play the classic memory matching game using your own photos to train your memory. With the Base Converter, you can easily convert numbers from one base to another. Finally, the Modulo Calculator allows you to quickly calculate the modulo of two numbers.
minimal_mistakes_skin: contrast
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
 


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  avatar : "/assets/images/MLZ_Logo2015.png"
  bio    : "All apps by MLZ in one place – ready for you to explore and enjoy."

footer:
  links:
    - label: "Imprint / Impressum + Haftungsausschluss"
      icon: "fab fa-fw fa-twitter-square"
      url: "/impressum/"
copyright: "Milos Lukas Ziolkowski"
atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/